name: lucadev_porforlio
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  go_router: ^14.1.4

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
fonts:
  - family: Manrope
    fonts:
      - asset: assets/font/manrope-latin-700-normal.ttf
        weight: 700
      - asset: assets/font/manrope-latin-800-normal.ttf
        weight: 800
